version : "3.8"

services:
  web:
    build: ./ewl/
    # command: python manage.py runserver 0.0.0.0:8000
    entrypoint: run.sh
    volumes:
      - ./ewl/:/usr/src/app/
    ports:
      - 8000:8000
    container_name: backend-ewl-server
    